import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import SortWindow from '../components/sortWindow';
import { bubbleSort, insertionSort, selectionSort, mergeSort, quickSort} from '../public/algorithms'
import { useState, useEffect } from 'react';
import { Typography } from '@material-ui/core';

export default function Home() {
  const [sortTypes, setSortTypes] = useState([]);
  const [inputArray, setInputArray] = useState([]);
  const [isReady, setIsReady] = useState(false);
  const [isRunning, setIsRunning] = useState(false);
  const [toggleChange, setToggleChange] = useState(true);

  const welcomeMessage =  "Hello! Welcome to Visual Sorting App!\nLet's get you started in 3 steps:\n" +
                          "Step 1: Input - You can input your own array if you want. The default option is a random array generated by us\n" +
                          "Step 2: Algorithms - Simply choose the sorting algorithms you would like to see in action! You can choose and unchoose each algorithm\n" +
                          "Step 3: Set parameters and run! You should see your number array visualised below\n" +
                          "You can pause half-way. After all is done, you should see your array sorted\n";

  // Elements in the array is an object with 2 fields: value and isChose. value is the numeric value of the element, isChosen signifies whether value isChosen.
  function getSortFunction(sortType) {
    let sortFunction;
    switch (sortType) {
      case "Bubble":
        sortFunction = bubbleSort;
        break;
      case "Insertion":
        sortFunction = insertionSort;
        break;
      case "Selection":
        sortFunction = selectionSort;
        break;
      case "Merge":
        sortFunction = mergeSort;
        break;
      case "Quick":
        sortFunction = quickSort;
        break;
      default:
        sortFunction = bubbleSort;
        break;
    }
    return sortFunction;
  }

  function resetInputArr() {
    let tempArr = inputArray;
    for (let i = 0; i < tempArr.length; i++) {
      tempArr[i].isSorted = false;
    }
    setInputArray(tempArr);
  }

  var displayStr = "[ ";
  for (let i = 0; i < inputArray.length; i++) {
    displayStr += inputArray[i].value + " ";
  }
  displayStr += "]";
  displayStr = "Input array: " + displayStr;

  var displaySortTypes = "[ ";
  for (let i = 0; i < sortTypes.length; i++) {
    displaySortTypes += sortTypes[i] + " ";
  }
  displaySortTypes += "]";
  displaySortTypes = "Sort types: " + displaySortTypes;
  
  const setInputToggleReady = function(newArray) {
    if (isReady) {
      setIsReady(false);
    }

    if (isRunning) {
      setIsRunning(false);
    }

    setInputArray(newArray);
    if (newArray.length > 0) {
      setIsReady(true);
    }
  }

  const setSortTypeToggleReady = function(arr) {
    if (isRunning) {
      setIsRunning(false);
    }

    if (isReady) {
      setIsReady(false);
    }

    setSortTypes(arr);
  }

  const setRunningToggleReady = function(bool) {
    if (!isReady) {
      setIsReady(true);
    }

    resetInputArr();
    
    setIsRunning(bool);
  }

  const deepCopyArray = function(arr) {
    let newArr = [];
    for (let i = 0; i < arr.length; i++) {
      newArr.push(Object.assign({}, arr[i]));
    }
    return newArr;
  }

  return (
    <div className={styles.page_container}>
      <Head>
        <title>Visual Sorting App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="body1" style={{whiteSpace: 'pre-line'}}>{welcomeMessage}</Typography>
      <Header sortTypes={sortTypes} setSortTypes={setSortTypeToggleReady} setInputArray={setInputToggleReady} isReady={isReady} setIsReady={setIsReady} isRunning={isRunning} setRunning={setRunningToggleReady} />
      <div className={styles.info_box}>
        <Typography>{displaySortTypes.length > 3 ? displaySortTypes : ""}</Typography>
        <Typography noWrap='true'>{displayStr.length > 3 ? displayStr : ""}</Typography>
      </div>
      {isReady 
        ? sortTypes.map((sortType) => 
          <SortWindow key={sortType} sortMethodName={sortType} sortMethodFunction={getSortFunction(sortType)} elementArray={deepCopyArray(inputArray)} setArray={setInputArray} isRunning={isRunning} />
          )
        : <div></div>}
    </div>
  ) 
}
